[build]
builder = "nixpacks"
buildCommand = "npx convex deploy --cmd 'npm run build'"

[deploy]
startCommand = "pnpm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"

[phases.setup]
nixPkgs = ["nodejs_18", "pnpm-9_x"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]
