[build]
builder = "nixpacks"
buildCommand = "pnpm install --no-frozen-lockfile && npx convex deploy --cmd 'pnpm run build'"

[deploy]
startCommand = "pnpm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"

[phases.setup]
nixPkgs = ["nodejs_22", "pnpm-9_x"]

[install]
cmds = ["pnpm install --no-frozen-lockfile"]
