[build]
builder = "nixpacks"
buildCommand = "pnpm install --no-frozen-lockfile && npx convex deploy --cmd 'npm run build'"

[deploy]
startCommand = "pnpm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]
